### ISSUE TITLE
Feature Request: Add notification in combat

### ISSUE THREAD

**Issue by Vestium-R** [reyzor1991/foundry-vtt-pf2e-notification#1]
I've added the following to my module on my end but it would be amazing to have this engrained in the main module as a togglable feature

This prevents the situation where a player has equipped more items than they can carry and enters combat. In the current module, the hook is based on an item update, so if the user tries to equip something, it flags it. However, if the user enters combat but never changes their items equipped status (i.e.: it was already being wielded) the player can have many items equipped without notice

The below code will check on each turn change in combat for each user - filtering shields, weapons, and torches (more can be added pretty easily)

```
Hooks.on("updateCombat",` async (combat, data) => {
    const combatentID = combat.current.tokenId;
    let token = canvas.scene.tokens.get(combatentID);
    let actor = token.actor;
    

  const shield = actor.itemTypes.equipment.filter(i => i.system.armor?.type === "shield" && i.system.equipped.carryType === "held");
  const weapons = actor.itemTypes.weapon.filter(i => i.name.toLowerCase() !== "unarmed attack" && i.system.equipped.carryType === "held");
  const torches = actor.itemTypes.consumable.filter(i => i.name.toLowerCase() === "torch");
  
  
  const items = [];
      if (shield) items.push(...shield);
      if (weapons) items.push(...weapons);
      if (torches) items.push(...torches);
      
      let handsequipped = items.reduce(function (s, a) {
        return s + a.system.equipped.handsHeld;
    }, 0);
        
     if (handsequipped > 2)
     {
            ui.notifications.warn(`${actor.name} is currently wielding ${handsequipped} 'hands' worth of items`);    
     }
});
```

**Comment by reyzor1991** [comment]
Done
