### ISSUE TITLE
Buckler should count as a free hand

### ISSUE THREAD

**Issue by LTErnis** [reyzor1991/foundry-vtt-pf2e-notification#2]
Hey Reyzor,

It's not a big deal, but if you have the time maybe you could look into implementing this somehow? The buckler is shown as occupying a hand, however, you can hold anything you want in that hand together with the buckler. It only matters if you try to Raise the buckler. https://2e.aonprd.com/Shields.aspx?ID=1 So the warning should not pop up unless you are trying to raise it while holding other 2 items.

Thanks for great modules :)

**Comment by reyzor1991** [comment]
Done

**Comment by LTErnis** [comment]
You're the best! Thanks :D
