### ISSUE TITLE
v12 Compatibility

### ISSUE THREAD

**Issue by Peach774** [reyzor1991/foundry-vtt-pf2e-notification#3]
Foundry lists this module as incompatible with v12 when asking it to preview compatibility.

**Comment by HonzoNebro** [comment]
You can use the module but it doesn't notify at all

**Comment by reyzor1991** [comment]
https://github.com/reyzor1991/foundry-vtt-pf2e-notification/assets/6688366/a89c576d-16ec-4045-950a-b7665433814c
